# Generated by Django 4.1.2 on 2022-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('password1', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
