# Generated by Django 4.1.2 on 2022-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
