# Generated by Django 4.1.2 on 2022-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_address_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bookname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('pub_count', models.ManyToManyField(to='base.published')),
            ],
        ),
    ]
